### ISSUE TITLE
Counting Spaces

### ISSUE THREAD

**Issue by GBrew252** [SLU-TMI/TextMining.jl#84] opened 2015-04-08 02:13 UTC
The 50 most frequent features table Mark shared from the EEBO cluster test seems to show that we're counting spaces. Either the most or second most frequent feature in the Ignatius, Godwin, Cavendish, and Rawley texts is an empty double quotation mark: ("",63), ("",40), ("",859), ("",67). Does this mean spaces are being used, or is this a notation for something else? In any case, that feature is not a word.

**Comment by mtabor150** [comment] 2015-04-08 13:53
These arn't spaces, they are nothing strings.  Spaces would be " " (space between quotes), these are "" (consecutive quotes).  I'm guessing these are caused by floating punctuation.  We are splitting on white space and then removing exterior punctuation so words go from "-word." to "word", but punctuation alone goes from "--," to "".  The simple fix is to set fv[""] = 0 after we make a feature vector.

**Comment by mtabor150** [comment] 2015-04-08 17:13
should be fixed now #85

**Closed as completed by mtabor150** 2015-04-08 17:13 UTC
Labels: bug
